<?php

namespace Database\Seeders;

use App\Models\Comment;
use App\Models\Label;
use App\Models\Labelmeta;
use App\Models\Media;
use App\Models\Post;
use App\Models\Postmeta;
use App\Models\User;
use Gemini\Laravel\Facades\Gemini;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class GeminiContentSeeder extends Seeder
{
    private function cleanGeminiJson(string $text): string
    {
        // hapus codeblock ```json atau ```
        $text = preg_replace('/```json/i', '', $text);
        $text = preg_replace('/```/i', '', $text);

        // trim
        return trim($text);
    }

    public function run(): void
    {
        // ============================================
        // USER
        // ============================================
        $user = User::first() ?? User::create([
            'name' => 'AI Author',
            'email' => 'ai@example.com',
            'password' => bcrypt('password'),
        ]);

        // ============================================
        // ASK GEMINI: CREATE CATEGORIES + TAGS
        // ============================================
        $taxPrompt = "
        Buatkan 5 kategori blog dan 10 tags.
        Format JSON tanpa penjelasan:
        {
            \"categories\": [\"...\"],
            \"tags\": [\"...\"]
        }";

        $taxResponse = Gemini::generativeModel('gemini-2.0-flash')->generateContent($taxPrompt)->text();
        $clean = $this->cleanGeminiJson($taxResponse);
        $taxonomy = json_decode($clean, true);
        //dd($taxResponse);
        if (!$taxonomy || !isset($taxonomy['categories'])) {
            throw new \Exception("Failed to parse taxonomy from Gemini.");
        }

        // ============================================
        // CREATE CATEGORIES
        // ============================================
        $categoryModels = collect([]);
        foreach ($taxonomy['categories'] as $cat) {
            $model = Label::create([
                'taxonomy' => 'category',
                'name' => $cat,
                'slug' => Str::slug($cat),
            ]);

            Labelmeta::create([
                'label_id' => $model->id,
                'meta_key' => 'color',
                'meta_value' => fake()->hexColor(),
            ]);

            $categoryModels->push($model);
        }

        // ============================================
        // CREATE TAGS
        // ============================================
        $tagModels = collect([]);
        foreach ($taxonomy['tags'] as $tag) {
            $model = Label::create([
                'taxonomy' => 'tag',
                'name' => $tag,
                'slug' => Str::slug($tag),
            ]);

            Labelmeta::create([
                'label_id' => $model->id,
                'meta_key' => 'color',
                'meta_value' => fake()->hexColor(),
            ]);

            $tagModels->push($model);
        }


        // ============================================
        // MEDIA (10 dummy images from picsum.photos)
        // ============================================
        $mediaModels = collect([]);

        for ($i = 1; $i <= 10; $i++) {

            // Gambar random stabil
            $url = "https://picsum.photos/seed/demo{$i}/1200/800";
            echo "Scraping $url \n";

            $image = Http::withOptions(['allow_redirects' => true])->timeout(20)->get($url);

            if ($image->successful()) {

                $filename = "demo-$i.jpg";
                $localPath = "$filename";


                // Simpan file ke storage/app/public
                Storage::disk('public')->put($localPath, $image->body());


                $dbPath = "/storage/$filename";

                $mediaModels->push(Media::create([
                    'mime'     => 'image/jpeg',
                    'path'     => $dbPath,
                    'filename' => $filename,
                    'size'     => strlen($image->body()),
                    'user_id'  => $user->id,
                ]));
            }
        }


        // ============================================
        // POSTS GENERATED BY GEMINI
        // ============================================
        for ($i = 1; $i <= 6; $i++) {
            echo "Generating post $i\n";

            $postPrompt = "
            Buatkan artikel blog bertema teknologi modern & pengembangan web.
            Sertakan:
            - Judul unik
            - Excerpt 1 paragraf
            - Isi artikel 3–5 paragraf
            - 3 komentar pendek

            Format EXACT seperti ini:
            ###TITLE###
            {judul}

            ###EXCERPT###
            {excerpt}

            ###CONTENT###
            {content}

            ###COMMENTS###
            - {komen1}
            - {komen2}
            - {komen3}
            ";

            $response = Gemini::generativeModel('gemini-2.0-flash')
                ->generateContent($postPrompt)
                ->text();

            // parse blocks
            preg_match('/###TITLE###([\s\S]*?)###EXCERPT###/', $response, $m1);
            preg_match('/###EXCERPT###([\s\S]*?)###CONTENT###/', $response, $m2);
            preg_match('/###CONTENT###([\s\S]*?)###COMMENTS###/', $response, $m3);
            preg_match('/###COMMENTS###([\s\S]*)/', $response, $m4);

            $title = trim($m1[1] ?? "Untitled");
            $excerpt = trim($m2[1] ?? "");
            $content = trim($m3[1] ?? "");
            $commentLines = explode("\n", trim($m4[1] ?? ""));

            $comments = collect($commentLines)
                ->map(fn($c) => trim($c, "- \t"))
                ->filter()
                ->values();

            // ============================
            // SAVE POST
            // ============================
            $post = Post::create([
                'type' => 'post',
                'title' => $title,
                'slug' => Str::slug($title) . '-' . Str::random(5),
                'image' => $mediaModels->random()->path,
                'content' => $content,
                'excerpt' => $excerpt,
                'user_id' => $user->id,
            ]);

            // attach category & tags
            $post->labels()->attach($categoryModels->random()->id);
            $post->labels()->attach($tagModels->random(rand(2, 5))->pluck('id')->toArray());

            // post meta
            Postmeta::create([
                'post_id' => $post->id,
                'meta_key' => 'views',
                'meta_value' => rand(100, 5000),
            ]);

            // comments
            foreach ($comments as $c) {
                Comment::create([
                    'post_id' => $post->id,
                    'user_id' => $user->id,
                    'content' => $c,
                ]);
            }
        }

        echo "Gemini Full Seeder executed successfully.\n";
    }
}
